AllCops:
  TargetRubyVersion: 2.3

MethodLength:
  Max: 200

LineLength:
  Max: 160

AbcSize:
  Max: 220

FileName:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

# ruby 2.1, 2.2 support
Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

# highly opinionated, subject to false positives, and likely to break valid code
Style/FormatStringToken:
  Enabled: false

# testing
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'test/**/*'
